### ISSUE TITLE
rlottie 0.2 freetype overflow. This bug appears when processing several VK stickers

### ISSUE THREAD

**Issue by umerov1999** [Aghajari/AXrLottie#10]
![Screenshot_20210219_215502](https://user-images.githubusercontent.com/3888404/108548900-8050bf80-72fd-11eb-8607-f06d7fdb9628.png)

**Comment by Aghajari** [comment]
Hi @umerov1999 ,
You should ask this on rlottie repo.
https://github.com/Samsung/rlottie

The first release applies telegram edits 
https://github.com/Aghajari/AXrLottie/releases/tag/v1.0.0-alpha
