### ISSUE TITLE
Can't assemble

### ISSUE THREAD

**Issue by hantrungkien** [Aghajari/AXrLottie#4]
@Aghajari Please help me to pre-release

```
/home/jitpack/build/AXrLottie/src/main/cpp/src/vector/vdrawhelper_neon.cpp:17: error: undefined reference to 'pixman_composite_src_n_8888_asm_neon'
/home/jitpack/build/AXrLottie/src/main/cpp/src/vector/vdrawhelper_neon.cpp:26: error: undefined reference to 'pixman_composite_over_n_8888_asm_neon'
```

This is the full log: https://jitpack.io/com/github/hantrungkien/AXrLottie/1.0.4-alpha01/build.log

Many thansk!

**Comment by Aghajari** [comment]
Hi @hantrungkien ,
Try to comment this two lines.
i just tested it and works fine.

`cpp/src/vector/vdrawhelper_neon.cpp` :

```cpp
#if defined(__ARM_NEON__)

#include "vdrawhelper.h"

extern "C" void pixman_composite_src_n_8888_asm_neon(int32_t w, int32_t h,
                                                     uint32_t *dst,
                                                     int32_t   dst_stride,
                                                     uint32_t  src);

extern "C" void pixman_composite_over_n_8888_asm_neon(int32_t w, int32_t h,
                                                      uint32_t *dst,
                                                      int32_t   dst_stride,
                                                      uint32_t  src);

void memfill32(uint32_t *dest, uint32_t value, int length)
{
    // pixman_composite_src_n_8888_asm_neon(length, 1, dest, length, value);
}

static void color_SourceOver(uint32_t *dest, int length,
                                      uint32_t color,
                                     uint32_t const_alpha)
{
    //if (const_alpha != 255) color = BYTE_MUL(color, const_alpha);

    //pixman_composite_over_n_8888_asm_neon(length, 1, dest, length, color);
}

void RenderFuncTable::neon()
{
    updateColor(BlendMode::Src , color_SourceOver);
}
#endif

```

**Comment by hantrungkien** [comment]
@Aghajari Yes, I have also tried but are you sure it will be worked on the Arm Neon Arch? Could you please let me know how do you run?

**Comment by Aghajari** [comment]
i'm not sure, i don't even know why is this happening, 
i'm running this on MacOS v11.2 Beta and everything works fine.

if you don't wanna change c/c++ codes, you can also use compiled files (.so) in output aar

[AXrLottie-release.aar](https://github.com/Aghajari/AXrLottie/blob/master/AXrLottie/AXrLottie-release.aar)

i've just updated it 10min ago. (https://github.com/Samsung/rlottie/commit/bd4c4e1f844c3c54378eada915f1d6e851ed39d2)

**Comment by hantrungkien** [comment]
@Aghajari very strange... I have tried some various ndk versions but still can't run ./gradlew assembleDebug. What is the ndk version on your you side?

Ah do you know how to use .tgs file? As I know, Telegram use sticker under .tgs format.

**Comment by Aghajari** [comment]
NDK 20.0.5594570

`.tgs` files are kinda a `.zip` file which contains json file.
You just need to add a new [FileExtension](https://github.com/Aghajari/AXrLottie#fileextension) for tgs files. (extension=".tgs")

EDIT :
`.tgs` files are GZip, v1.0.5 supports this.

**Comment by hantrungkien** [comment]
@Aghajari It just is a zip file contains json file with purpose reduce capacity to speed up download right?

**Comment by Aghajari** [comment]
@hantrungkien Yes + it's really smaller than a json file

**Comment by hantrungkien** [comment]
@Aghajari many thanks. Could you please list my name to contributors list?
