### ISSUE TITLE
version 1.0.4 seem be 1.0.3 on bintray

### ISSUE THREAD

**Issue by hantrungkien** [Aghajari/AXrLottie#5]
Please help me check it

```
implementation 'com.aghajari.rlottie:AXrLottie:1.0.4'
```

**Comment by Aghajari** [comment]
Yeh, right
i just sent a message to bintray, they will fix it soon
otherwise i'll upload it again as v1.0.5. 

Thanks for letting me know this!

**Comment by Aghajari** [comment]
Fixed
