### ISSUE TITLE
[Request] Should support tgs - telegram animation sticker file 

### ISSUE THREAD

**Issue by chihung93** [Aghajari/AXrLottie#6]
I think Samsung - Rlottie support TGS, so you should add more feature to support this kind of format.
Thanks.

@Aghajari

**Comment by hantrungkien** [comment]
@chihung93 Yes. It just is a gzip file contains json file with purpose reduce capacity to speed up download. We will support it soon. 
https://github.com/Aghajari/AXrLottie/issues/4#issuecomment-772275432

**Comment by Aghajari** [comment]
Done

```java
AXrLottie.addFileExtension(new GZipFileExtension(".tgs"));
```
